### ISSUE TITLE
Exclude requested packages/dirs from being mutated

### ISSUE THREAD

**Issue by alessio-perugini** [go-gremlins/gremlins#167]
This feature will allow a user to exclude some directories from being mutated.

We can pass a flag with a list of dirs to be excluded by gremlins unleash

```bash
gremlin unleash --exclude-dirs="./dir1,./dir2,./dir3"
```

Config file:
```yaml
unleash:
  exclude-dirs:
  - "./dir1"
  - "./dir2"
  - "./dir3"
```

What do you think about that?

**Comment by k3rn31** [comment]
I'm not sure if it is better to exclude dirs or packages...
Also, we have to be careful on how it plays with the recently added --coverpkg flag.

**Comment by k3rn31** [comment]
Regarding this feature, I was thinking of something more flexible.

To exclude specific mutators for paths:
```yaml
excludes:
  - path: <path regex>
    mutators:
      - mutator1
      - mutator2
```
In this case we can have a list of specific path or regex matching paths. For each, we can have a specific list of mutators to match (if not specified will be *all* mutators).

Same concept can be applied to packages:
```yaml
excludes:
  - package: <package regex>
    mutators:
      - mutator1
      - mutator2
```
