### ISSUE TITLE
Mutation gets erroneously marked as killed

### ISSUE THREAD

**Issue by hknutzen** [go-gremlins/gremlins#184]
### Bug Description

I run gremlins in integration mode.
When run on the whole project, a mutation gets correctly marked as LIVED.
But when run on the package where the mutated files is located, the same mutation is marked as KILLED by mistake.

### To Reproduce

1. `git clone -b gremlins-issue-184 https://github.com/hknutzen/Netspoc.git`
2. `cd Netspoc/go`
3. #for simplicity, only enable one mutation: "Invert logical operators"
 `cat > .gremlins.yml <<END`
```
mutants:
  arithmetic-base:
    enabled: false
  conditionals-boundary:
    enabled: false
  conditionals-negation:
    enabled: false
  increment-decrement:
    enabled: false
  invert-negatives:
    enabled: false
  invert-logical:
    enabled: true
  invert-loopctrl:
    enabled: false
  invert-bitwise:
    enabled: false
END
```

4. gremlins run -i --coverpkg ./pkg/...
 shows:
```
Starting...
Gathering coverage... done in 18.834607584s
      KILLED INVERT_LOGICAL at pkg/api/modify.go:199:42
      KILLED INVERT_LOGICAL at pkg/api/modify.go:199:21
      KILLED INVERT_LOGICAL at pkg/api/modify.go:200:19
      KILLED INVERT_LOGICAL at pkg/api/modify.go:256:17
  NOT VIABLE INVERT_LOGICAL at pkg/api/path.go:249:23
      KILLED INVERT_LOGICAL at pkg/api/path.go:250:49
      KILLED INVERT_LOGICAL at pkg/api/path.go:250:21
       LIVED INVERT_LOGICAL at pkg/api/path.go:394:26  #OK
     ... <-- process may be interrupted now
```
5. cd pkg/api
6. gremlins run -i --coverpkg ./pkg/...
 shows:
```
Starting...
Gathering coverage... done in 18.470632631s
      KILLED INVERT_LOGICAL at modify.go:199:42
      KILLED INVERT_LOGICAL at modify.go:199:21
      KILLED INVERT_LOGICAL at modify.go:200:19
      KILLED INVERT_LOGICAL at modify.go:256:17
      KILLED INVERT_LOGICAL at path.go:249:23
      KILLED INVERT_LOGICAL at path.go:250:49
      KILLED INVERT_LOGICAL at path.go:250:21
      KILLED INVERT_LOGICAL at path.go:394:26  #BAD
  ....
```

### Found behaviour

Gremlins marks line `pkg/api/path.go:394:26` as LIVED, when run on the whole project,
but it marks the same line as KILLED, when run in directory `pkg/api`.

### Expected behaviour

Line `path.go:394:26` should in both cases be marked as LIVED.

### Operating System

- OS: Ubuntu
- Version 22.04.1
